### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ayoubkhan558-zz** [michaeldoye/WaNG#2]
I can get the products I have the following error
I am working with Ionic 4 And Angular 7

![localhost_345_(Galaxy Note 3) (1)](https://user-images.githubusercontent.com/20210961/57223259-e97b1c00-701e-11e9-8da9-79b921a68cd6.png)

**Comment by michaeldoye** [comment]
It seems your error is related to `aws/sign2` module... Not this module.
